In [1]:
#Cossio Jose

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
dataset = pd.read_csv('diabetes-dataset.csv')
dataset

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,2,138,62,35,0,33.6,0.127,47,1
1,0,84,82,31,125,38.2,0.233,23,0
2,0,145,0,0,0,44.2,0.630,31,1
3,0,135,68,42,250,42.3,0.365,24,1
4,1,139,62,41,480,40.7,0.536,21,0
...,...,...,...,...,...,...,...,...,...
1995,2,75,64,24,55,29.7,0.370,33,0
1996,8,179,72,42,130,32.7,0.719,36,1
1997,6,85,78,0,0,31.2,0.382,42,0
1998,0,129,110,46,130,67.1,0.319,26,1
1999,2,81,72,15,76,30.1,0.547,25,0

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               2000 non-null   int64
 1   Glucose                   2000 non-null   int64
 2   BloodPressure             2000 non-null   int64
 3   SkinThickness             2000 non-null   int64
 4   Insulin                   2000 non-null   int64
 5   BMI                       2000 non-null   float64
 6   DiabetesPedigreeFunction  2000 non-null   float64
 7   Age                       2000 non-null   int64
 8   Outcome                   2000 non-null   int64
dtypes: float64(2), int64(7)
memory usage: 140.8 KB

In [6]:
dataset.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [7]:
#Se crean las variables y y X para realizar las operaciones
#La variable de salida Y es la columna "Outcome"
#La variable X serian todas las demas columnas.
X = dataset.iloc[:,:-1]
y = dataset.iloc[:,-1]

In [8]:
X

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,2,138,62,35,0,33.6,0.127,47
1,0,84,82,31,125,38.2,0.233,23
2,0,145,0,0,0,44.2,0.630,31
3,0,135,68,42,250,42.3,0.365,24
4,1,139,62,41,480,40.7,0.536,21
...,...,...,...,...,...,...,...,...
1995,2,75,64,24,55,29.7,0.370,33
1996,8,179,72,42,130,32.7,0.719,36
1997,6,85,78,0,0,31.2,0.382,42
1998,0,129,110,46,130,67.1,0.319,26
1999,2,81,72,15,76,30.1,0.547,25

In [9]:
y

0       1
1       0
2       1
3       1
4       0
       ..
1995    0
1996    1
1997    0
1998    1
1999    0
Name: Outcome, Length: 2000, dtype: int64

In [18]:
#Conversion a numpy array
X = np.array(X)
print(X)
print('==========')
y = np.array(y)
print(y)

[[2.00e+00 1.38e+02 6.20e+01 ... 3.36e+01 1.27e-01 4.70e+01]
 [0.00e+00 8.40e+01 8.20e+01 ... 3.82e+01 2.33e-01 2.30e+01]
 [0.00e+00 1.45e+02 0.00e+00 ... 4.42e+01 6.30e-01 3.10e+01]
 ...
 [6.00e+00 8.50e+01 7.80e+01 ... 3.12e+01 3.82e-01 4.20e+01]
 [0.00e+00 1.29e+02 1.10e+02 ... 6.71e+01 3.19e-01 2.60e+01]
 [2.00e+00 8.10e+01 7.20e+01 ... 3.01e+01 5.47e-01 2.50e+01]]
==========
[1 0 1 ... 0 1 0]

In [ ]:
#Reshape de las variables
X = X.reshape(-1,1)
print(X)
print('==========')
y = y.reshape(-1,1)
print(y)

In [10]:
#Segmentacion de los datos
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [11]:
X_train

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
1045,3,176,86,27,156,33.3,1.154,52
937,0,97,64,36,100,36.8,0.600,25
1658,2,123,48,32,165,42.1,0.520,26
529,0,111,65,0,0,24.6,0.660,31
895,4,184,78,39,277,37.0,0.264,31
...,...,...,...,...,...,...,...,...
835,5,99,54,28,83,34.0,0.499,30
1216,6,190,92,0,0,35.5,0.278,66
1653,4,95,64,0,0,32.0,0.161,31
559,11,85,74,0,0,30.1,0.300,35
684,5,136,82,0,0,0.0,0.640,69

In [12]:
y_train

1045    1
937     0
1658    0
529     0
895     1
       ..
835     0
1216    1
1653    1
559     0
684     0
Name: Outcome, Length: 1500, dtype: int64

In [13]:
#Escalando variables
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [14]:
X_train

array([[-0.1984574 ,  1.69829948,  0.86966378, ...,  0.12166535,
         2.06554698,  1.65399435],
       [-1.11724164, -0.7539766 , -0.24481351, ...,  0.54222308,
         0.37965447, -0.68142284],
       [-0.50471881,  0.05310161, -1.05534245, ...,  1.17906764,
         0.13620429, -0.5949259 ],
       ...,
       [ 0.10780402, -0.81605953, -0.24481351, ..., -0.03454181,
        -0.9562784 , -0.16244124],
       [ 2.25163392, -1.12647423,  0.26176708, ..., -0.26284458,
        -0.53328371,  0.18354649],
       [ 0.41406543,  0.45664071,  0.66703154, ..., -3.87964107,
         0.50137956,  3.12444221]])

In [15]:
#Entrenamiento con el modelo de Regresion Logistica
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [16]:
print(classifier.predict(sc.transform([[1,150,50,30,100,44.0,0.6,22]])))

[1]

C:\Users\Usuario\anaconda3\envs\IMT345\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [17]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

AttributeError: 'Series' object has no attribute 'reshape'